// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240104140343_table3")]
    partial class table3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsrTable1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Table1Balance")
                        .HasColumnType("int");

                    b.Property<string>("Table1Distillation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table1Production")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Table1Receipts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AsrTable1");
                });

            modelBuilder.Entity("AsrTable2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Balance")
                        .HasColumnType("int");

                    b.Property<int?>("Installments")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Products")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Receipts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AsrDistillationProducts");
                });

            modelBuilder.Entity("AsrTable3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsrTable3Balance")
                        .HasColumnType("int");

                    b.Property<int?>("AsrTable3Installments")
                        .HasColumnType("int");

                    b.Property<string>("AsrTable3Products")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AsrTable3Receipts")
                        .HasColumnType("int");

                    b.Property<string>("AsrTable3Supply")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AsrTable3");
                });
#pragma warning restore 612, 618
        }
    }
}
